STR_PENDING = "PENDING"
STR_IN_PROGRESS = "IN_PROGRESS"
STR_COMPLETED = "COMPLETED"

INT_PENDING = 1
INT_IN_PROGRESS = 2
INT_COMPLETED = 3

TASK_STATUS_STR_TO_INT = {
    STR_PENDING: INT_PENDING,
    STR_IN_PROGRESS: INT_IN_PROGRESS,
    STR_COMPLETED: INT_COMPLETED
}

TASK_STATUS_INT_TO_STR = {
    INT_PENDING: STR_PENDING,
    INT_IN_PROGRESS: STR_IN_PROGRESS,
    INT_COMPLETED: STR_COMPLETED
}