ROLE_USER = "USER"
ROLE_MANAGER = "MANAGER"
ROLE_ADMIN = "ADMIN"


PERMISSION_VIEW_ALL_USERS = "can_view_all_users"
PERMISSION_VIEW_ALL_TASKS = "can_view_all_tasks"
PERMISSION_CREATE_TASKS = "can_create_tasks"
PERMISSION_ASSIGN_TASK_TO_ANY_USER = "can_assign_task_to_any_user"
PERMISSION_ASSIGN_TASK_TO_USER = "can_assign_task_to_user"
PERMISSION_UPDATE_ANY_TASK = "can_update_any_task"
PERMISSION_DELETE_ANY_TASK = "can_delete_any_task"
PERMISSION_UPDATE_TASK_STATUS = "can_update_task_status"
PERMISSION_CREATE_ROLES = "can_create_roles"
PERMISSION_VIEW_ROLES = "can_view_roles"
PERMISSION_UPDATE_ROLES = "can_update_roles"
PERMISSION_DELETE_ROLES = "can_delete_roles"
PERMISSION_VIEW_TASKS = "can_view_tasks"
PERMISSION_VIEW_USER = "can_view_user"
PERMISSION_UPDATE_TASK = "can_update_task"
PERMISSION_DELETE_TASK = "can_delete_task"